[package]
name = "livemod"
version = "0.1.0"
edition = "2018"

[features]
derive = ["livemod-derive"]
disabled = []

[dependencies]
parking_lot = "0.11"
nanoserde = "0.1"
base64 = "0.13"

livemod-derive = { path = "../livemod-derive", optional = true }